name: Nuclei-VulnScanner

on:
  push:
    branches      - main

jobs:
  NucleiScan:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch target URLs
        run: |
          curl -o targets.txt 'https://web.archive.org/cdx/search/cdx?url=*.newegg.com&fl=original&collapse=urlkey'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Required Tools
        run: |
          go install -v github.com/projectdis/nuclei/v2/cmd/nuclei@latest
        shell: bash

      - name: Vulnerability Scanning
        run: |
          nuclei -l targets.txt -t templates/ -o nuclei_output.txt
        shell: bash
