name: Nuclei-VulnScanner

on:
  push:
    branches:
      - main

jobs:
  NucleiScan:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch target
        run: |
          curl -o targets.txt 'https://web.archive.org/cdx/search/cdx?url=*.newegg.com&fl=original&collapse=urlkey'

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Required Tools
        run: go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

      - name: Vulnerability Scanning
        run: nuclei -l targets.txt -/ -o nuclei_output.txt

      - name: Upload Nuclei Output as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Nuclei Output
          path: nuclei_output.txt
