name: Nuclei
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  targeturl: 'https://web.archive.org/cdx/search/cdx?url=*.fujcharity.ae&fl=original&collapse=urlkey'

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Nuclei
      run: |
        wget https://github.com/projectdiscovery/nuclei/releases/download/v2.4.0/nuclei_2.4.0_linux_amd64.tar.gz
        tar -xzvf nuclei_2.4.0_linux_amd64.tar.gz
        sudo mv nuclei /usr/local/bin/
    - name: scanning  
      run: |
        curl $DOMAIN -o targets.txt
        nuclei -l targets.txt | tee -a nuclei-scan-result.txt
      shell: bash
      
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Saving Result
        path: nuclei-scan-result.txt
