name: Nuclei-VulnScanner

on:
  push:
    branches:
      - main

jobs:
  NucleiScan:
    runs-on: ubuntu-latest
   :
      - name: Fetch target URLs
        run: |
          curl -o targets https://web.archive.org/cdx/search/cdx?url=*.newegg.com&fl=original&collapse=urlkey

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user "youremail@example.com"

      - name: Required Tools
        run: |
          export GOPRIVATE=github.com/projectdis/nuclei
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          go install -v github.com/projectdisuclei/v2/cmduclei@latest
        shell: bash

      - name: Vulnerability Scanning
        run: |
          nuclei -l targets.txt -t templates/ -o nuclei_output.txt
        shell: bash
